# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_sweep_generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 680)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.spectrogram_plot = PlotWidget(self.centralwidget)
        self.spectrogram_plot.setEnabled(True)
        self.spectrogram_plot.setGeometry(QtCore.QRect(10, 400, 600, 220))
        self.spectrogram_plot.setObjectName("spectrogram_plot")
        self.temporal_plot = PlotWidget(self.centralwidget)
        self.temporal_plot.setGeometry(QtCore.QRect(10, 240, 600, 150))
        self.temporal_plot.setObjectName("temporal_plot")
        self.params_box = QtWidgets.QGroupBox(self.centralwidget)
        self.params_box.setGeometry(QtCore.QRect(60, 10, 201, 211))
        self.params_box.setObjectName("params_box")
        self.label = QtWidgets.QLabel(self.params_box)
        self.label.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.params_box)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 91, 21))
        self.label_2.setObjectName("label_2")
        self.begfreq_textedit = QtWidgets.QLineEdit(self.params_box)
        self.begfreq_textedit.setGeometry(QtCore.QRect(100, 30, 91, 22))
        self.begfreq_textedit.setObjectName("begfreq_textedit")
        self.endfreq_textedit = QtWidgets.QLineEdit(self.params_box)
        self.endfreq_textedit.setGeometry(QtCore.QRect(100, 60, 91, 22))
        self.endfreq_textedit.setObjectName("endfreq_textedit")
        self.dur_textedit = QtWidgets.QLineEdit(self.params_box)
        self.dur_textedit.setGeometry(QtCore.QRect(100, 90, 91, 22))
        self.dur_textedit.setObjectName("dur_textedit")
        self.label_3 = QtWidgets.QLabel(self.params_box)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 91, 21))
        self.label_3.setObjectName("label_3")
        self.srate_textedit = QtWidgets.QLineEdit(self.params_box)
        self.srate_textedit.setGeometry(QtCore.QRect(100, 120, 91, 22))
        self.srate_textedit.setObjectName("srate_textedit")
        self.label_4 = QtWidgets.QLabel(self.params_box)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 91, 21))
        self.label_4.setObjectName("label_4")
        self.savesweep_button = QtWidgets.QPushButton(self.params_box)
        self.savesweep_button.setGeometry(QtCore.QRect(100, 170, 93, 28))
        self.savesweep_button.setObjectName("savesweep_button")
        self.label_5 = QtWidgets.QLabel(self.params_box)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 91, 28))
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.params_box)
        self.line.setGeometry(QtCore.QRect(30, 140, 141, 41))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gensweep_button = QtWidgets.QPushButton(self.centralwidget)
        self.gensweep_button.setGeometry(QtCore.QRect(305, 50, 270, 51))
        self.gensweep_button.setObjectName("gensweep_button")
        self.playsweep_button = QtWidgets.QPushButton(self.centralwidget)
        self.playsweep_button.setGeometry(QtCore.QRect(305, 120, 270, 51))
        self.playsweep_button.setObjectName("playsweep_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.params_box.setTitle(_translate("MainWindow", "Sweep parameters"))
        self.label.setText(_translate("MainWindow", "Beginning freq."))
        self.label_2.setText(_translate("MainWindow", "Ending freq."))
        self.label_3.setText(_translate("MainWindow", "Duration"))
        self.label_4.setText(_translate("MainWindow", "Sampling freq."))
        self.savesweep_button.setText(_translate("MainWindow", "Browse..."))
        self.label_5.setText(_translate("MainWindow", "Saving location"))
        self.gensweep_button.setText(_translate("MainWindow", "Generate sweep"))
        self.playsweep_button.setText(_translate("MainWindow", "Play sweep"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
